# Generated by Django 5.0.6 on 2024-06-25 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='public',
        ),
    ]
