# Generated by Django 5.0.6 on 2024-06-29 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_remove_contact_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
    ]
