# Generated by Django 5.0.6 on 2024-06-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SosialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('url_inst', models.URLField(blank=True, verbose_name='Instagram')),
                ('url_face', models.URLField(blank=True, verbose_name='Facebook')),
                ('url_teleq', models.URLField(blank=True, verbose_name='Telegram')),
                ('sosial_image', models.ImageField(upload_to='sosial_media')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
