# Generated by Django 5.0.6 on 2024-06-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeshop', '0003_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Derc edilme tarixi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Yenilenme tarixi'),
        ),
    ]
